<!-- Header -->
<header class="w3-display-container w3-content w3-center" style="max-width:1500px">
  <img class="w3-image" src="Imgs/macdemarco7_Danny-Cohen_Cigarette-Heaven.jpg" alt="Skullhead" width="600" height="600">

  <main role="main" class="container">
  <div class="row">
    <div class="col-md-12 blog-main">
      <h3 class="pb-4 mb-4 font-italic border-bottom">
      Mac DeMarco 
      </h3>

      <div class="blog-post">
        <h2 class="blog-post-title">Descubriendo al verdadero Mac DeMarco</h2>
        <p class="blog-post-meta">Mayo 23, 2017 by <a href="index.html">Skullhead</a></p>

        <p>Tras años de ser visto como el tipo divertido de la música, <i>Mac</i> muestra su lado humano en su nuevo álbum <i>'This Old Dog'.</p></i>
        <hr>
        <p>Durante los últimos cinco años, <strong>Mac DeMarco</strong> ha estado tratando de mostrar su lado real. Algunos artistas crean un personaje y se quedan con él, o en algún momento terminan dividiéndose en pequeños fragmentos de identidades distintas. Pero la personalidad de <i>DeMarco</i> —si es como lo quieres llamar— 
            fue creada esencialmente sin que él tuviera injerencia en ello. <strong>"Tal vez pinté alguna imagen medio extraña",</strong> me cuenta cuando nos reunimos en el este de <i>Londres,</i> considerando cómo pudo haber nacido esa percepción de él. <strong>"Pero es algo que tienes que aceptar, porque está fuera de tus manos. Es como hacer música: las canciones salen y dejan de ser tuyas".</strong></p>
        <blockquote>
          <p>Es difícil saber cuándo fue que la reputación del cantautor canadiense de <i>lo-fi</i> se fue de sus manos en primer lugar. Como si fuera un personaje de dibujos animados, el <strong>DeMarco</strong> de los chistes bobos, de las bromas sobre pedos, y lleno de payasadas en general, ha sido en parte una gran exageración. No que no tenga que ver nada con esa reputación. 
              Para demostrar que <strong>DeMarco</strong> realmente es un ejemplo del humor absurdo, su participación como presentador invitado en <strong>MTV's Weird Vibes</strong> es evidencia suficiente ­—su falso acento británico, sus chistes locales, y el tipo de conversación torpe e incómoda que podrías esperar de un conductor de televisión profesional. Y en el raro caso de que seas una persona naturalmente chistosa, 
              la gente espera que seas chistoso todo el tiempo. <strong>Hablamos de un tipo que hizo un <i>sketch</i> fingiendo ser un tipo llamado <i>Dave Fuck,</i></strong> que pasaba la vida enseñándole a coches cómo estacionarse de reversa. Lo que en esencia es humor escolar, de alguna manera no se ve como crudo o estúpido —es muy gracioso.</p>
        <blockquote>
            <p>Pero existe una diferencia entre el <strong>Mac</strong> de los memes y el tipo sincero que escuchas en sus discos. Hasta ahora, ha sido difícil de descifrar entre los dos. Justo cuando busca instalarse en un surco de composiciones honestas y sin pretensiones, lanza grandes dosis de sátira. Por ejemplo, ahí está <strong>"Passing Out The Pieces,"</strong> <i>de 2014</i> —una canción sobre no ser propiedad de los extraños, ni un bufón <i>24/7,</i> 
                que también está acompañada de un video donde mata a sus amigos y da a luz en una tina llena de colores. Es un humor torcido que parece no poder resistir.</p>
        <blockquote>
            <p>Sin embargo, con el lanzamiento de su álbum más reciente <strong>This Old Dog</strong> <i>el pasado 5 de mayo,</i> el lado juguetón se mantiene en un bajo perfil. En gran parte del disco, <strong>DeMarco</strong> está esencialmente hablando consigo mismo, mirándose en un espejo, viendo qué hay dentro de su cabeza. <strong>El álbum en sí tiene sus raíces en una coyuntura familiar y, específicamente, toca el tema del padre de <i>DeMarco,</i> que recientemente se enfermó de gravedad.</p></strong>
        <blockquote>
            <p>No que puedas percibir este lado introspectivo y emocional de <strong>Mac</strong> en la promo que le ha hecho al disco. En una sesión en la que interpreta el tema que le da nombre al disco <i>This Old Dog,</i> se puede ver a <strong>DeMarco</strong> tocando en medio de una estética canina. <strong>"Podrías preguntarte, ¿por qué Mac está en Groom Dog City? ¿Por qué?",</strong> dice, al presentar la canción. <i>"Bueno", suspira, "probablemente porque la siguiente canción que voy a tocar se llama 'This Old Dog'...</i> 
                Y aunque no esté hablando de un perro real en la canción, esta es probablemente será el tipo de prensa que haré por los próximos dos años". Es una broma envuelta en un hartazgo real. <i>Le entra al juego, viéndole el lado divertido, pero también hay una sensación de que se está cansando de los chistoretes.</i> <strong>Ha sido el chico gracioso durante media década —quizá ya haya sido suficiente.</strong></p>
        <blockquote>
            <p>El mismo día en que se filmó esta sesión, se sentó conmigo en medio del <i>Beigel Bake</i> de <i>Brick Lane,</i> masticando lo que resulta ser su tercer <i>bagel</i> de cecina en las últimas 24 horas. Le enseñó las imágenes del <strong>#Bagelgate,</strong> una brutalmente hermosa encapsulación de la cultura británica que parece no entender. <strong>"Es mi culpa. Han pasado dos días desde que el <i>#Bagelgate</i> tomó por sorpresa al país, y como estamos en una tienda de <i>bagels,</i> pensé que a Mac el gracioso le gustaría este video."</strong> 
                <strong>"¿Ocho bagels? Eso le va a hacer cosas locas a tu estómago y a tu mente",</strong> dice, ofreciendo una especie de explicación sobre lo que lo estaba obligando ver. Pero está claro que preferiría dirigir el tema de la plática hacia su música.</p>
        <blockquote>
            <p>En un show acústico en <i>Londres</i> más tarde esa noche, felizmente le dice a la multitud cómo ha pasado el día haciendo prensa, algo que odia. Es fácil ver por qué, cuando en lugar de que le pregunten por sus discos, un día de promoción promedio consiste en estéticas de perros y videos virales de <i>bagels,</i> nada más por las risas. Es tentador ir a una entrevista con <strong>Mac DeMarco</strong> pensando que serás su mejor amigo al final de la misma. Es carismático en ese sentido. Y la verdad es que su personalidad es parte crucial de por qué se ha vuelto tan exitoso, 
                agotando las entradas de un lugar como la <i>Brixton Academy,</i> un lugar con capacidad para 4,900 personas, en cuestión de minutos. Sin embargo, a pesar de la prensa, ha intentado romper el mito de ser un tipo bidimensional y divertido, el cual está puesto para la actividad que le pongan enfrente.</p>
        <blockquote>
            <p>Hasta el año pasado, <strong>Mac</strong> vivía en el barrio <i>Far Rockaways,</i> parte del distrito de <i>Queens, en Nueva York.</i> En su mini álbum de 2015, <strong>Another One,</strong> eligió compartir su dirección con sus fans. <strong>"Dense una vuelta, les preparo una taza de café. Hasta pronto",</strong> dice al final de <strong>"My House On the Water".</strong> Esto podría parecer extraño viniendo de un tipo idolatrado por una horda de jóvenes que <i>porta camisas de franela, gorras de béisbol y fuma cigarrillos Viceroy en su honor.</i> Al volverse accesible en todo momento, se esperaría que estuviera a la altura de su personaje las <i>24/7.</i> 
                <strong>"Hubo momentos en que fue como, '¿Es una puta broma?'",</strong> admite. Su invitación para una taza de café fue aceptada ampliamente por los fans, que se presentaban en su casa borrachos a las 2 de la mañana. <strong>"Pero nunca me arrepentí de haberlo hecho. Fue genial conocer a tanta gente, y no pasó nada malo o raro".</strong> Como todos los encuentros con fans que tiene, <strong>Mac</strong> <i>era él mismo: relajado, despreocupado, no tanto el chistosito que uno puede creer que es por su reputación en internet.</i> En parte ese era el punto de compartir su dirección —<strong>disipar el mito.</p></strong>
        <blockquote>
            <p><strong>"Me visto como un personaje de caricaturas y uso la misma mierda todos los días —sólo porque soy flojo. Haces eso y la gente empieza a reconocerlo. Digo una vez 'Dios los bendiga' y se convierte en 'eso' que digo. Lo bueno de que vengan a conocerme, o incluso de conocer gente en los conciertos, es que tal vez esas personas tengan una percepción de quién soy, que tal vez sea cierta o tal vez no, pero en una situación cara a cara como esa, trato a todo el mundo como un ser humano y simplemente pasamos el rato", </strong> dice. <strong>"Para mí, es importante. Todo esa pose de celebridad, de banda sexy súper cool e inalcanzable, 
                es una puta mierda. Quiero desmitificar eso un poco".</strong> Cuando crecía en la ciudad de <i>Edmonton, Canadá,</i> <strong>Mac</strong> fue alguna vez ese niño obsesionado con la música, y se quedaba después de los conciertos a conocer a algunas de sus bandas favoritas locales. <strong>"Porque pude conocer a esas bandas que admiraba y decirles '¿Qué onda?', me di cuenta de que yo podía hacer lo mismo".</strong></p>
        <blockquote>
            <p><strong>This Old Dog</strong> hace un trabajo similar buscando desmitificar el lado desconocido de <strong>DeMarco.</strong> <i>Líricamente, no hace ningún truco. La mayoría de los temas que se tratan se abordan de manera directa, pero con la suficiente ambigüedad para no que no se sientan melodramáticos.</i> De todo lo que <strong>DeMarco</strong> aborda, el sentimiento de envejecer es el que más aparece. <strong>Es como un pensamiento persistente que no se puede sacar de la cabeza.</strong> <strong>"Dreams From Yesterday"</strong> es el sonido de un niño que le pega a lotería, sólo para terminar en un limbo. <strong>"Once your life set to settle down / Take a look around you, no more dreaming to be found 
                (Una vez que tu vida esté lista para asentarse / Echa un vistazo a tu alrededor, no hay más sueños que encontrar)",</strong> canta. <strong>"My Old Man"</strong> se refiere incluso de manera directa a la reputación que le precede. <strong>"Hay un precio para toda esa diversión",</strong> dice, como dos personalidades divididas que tienen una conversación privada. Definitivamente, <strong>DeMarco</strong> ha crecido. Pero no de una forma aburrida ni amargada. Aquellas partes relajadas de guitarra han ido mejorando, y estas son bien redondeadas con un flujo perfecto. Eso no quiere decir que no haya un sentido de la juventud que fluya a lo largo del álbum también, porque lo hay 
                —simplemente también existe la amenaza de la vejez, mirándote directamente en la cara, pujando por conseguir la ventaja.</p>
        <blockquote>
            <p><strong>Mac</strong> ha sido sincero antes —<strong>"Still Together"</strong> <i>de 2012</i> es una oda a su amor de la niñez <strong>Kiera "Kiki" McNally,</strong> con quien sigue a la fecha, mientras que <strong>"Let My Baby Stay"</strong> <i>de 2014</i> es un analiza el hecho de que ella podría ser expulsada de EE.UU. debido las leyes de migración. Sin embargo, es raro que sus canciones sean tan directas y autobiográficas. <strong>"No soy un gran letrista, así que no puedo hacer algo al estilo de <i>Bob Dylan</i> sin quedar como un idiota",</strong> insiste. <strong>"No soy como, <i>'Chicagoooo in October!'",</i></strong> añade, haciendo una divertida parodia de <i>Sun Kil Moon.</i> Así que —además del querer ofrecer un retrato más honesto de sí mismo— <strong>¿cuál es la razón de la nueva dirección de DeMarco?</strong></p>
        <blockquote>
            <p>Parte del nuevo enfoque tiene que ver con su mudanza a <i>Los Ángeles en 2016,</i> donde dejó la música de lado mientras se adaptaba a un nuevo lugar. <strong>"Estuve tres o cuatro meses adaptándome",</strong> recuerda. <strong>"Debido a que tenía más paz en ese sentido, me liberé del rol de borracho-que-toca-y-sale-de-fiesta-diario. Tener un gran espacio de tiempo alejado de todo eso cambió mi manera de ver las cosas. Por lo general tengo sólo un mes para desconectarme, y no me da tiempo de descomprimirme y pensar las cosas, o darme cuenta, "Ah, ¡tengo una familia!", pero cuando tienes mucho tiempo libre, retrocedes un poco y analizas lo que está pasando en tu vida. Maduras un poco sin realmente notarlo".</strong></p>
        <blockquote>
            <p>Escribir intermitentemente <i>en 2016 entre Nueva York y LA</i> coincidió con noticias sobre la enfermedad de su padre, que en ese momento estaba tomando un mal giro. Esto está documentado en <strong>"Watching Him Fade Away",</strong> la canción con la que cierra el nuevo disco, que también es el momento más notable del material. El padre de <strong>DeMarco</strong> rara vez estuvo en su vida, propenso al abuso de drogas y alcohol, apareciendo cada cierto tiempo a medida que su hijo crecía, pero nunca como parte central de su formación. Las canciones de <strong>Mac</strong> han relatado esto antes, pero <strong>"This Old Dog",</strong> y <strong>"Watching Him Fade Away"</strong> en particular, se enfrentan con la idea de despedirse de alguien que rara vez estuvo allí en primer lugar.</p>                
        <blockquote>
            <p><strong>"Y a pesar de que apenas se conocen, aún duele, ver cómo se desvanece",</strong> canta, destrozado entre la cama en la que se encuentra su papá y la puerta de salida. <i>Es la canción más generosamente honesta y desgarradora de <strong>Mac</strong> a la fecha.</i> <strong>"Lo curioso es que ahora se ha recuperado",</strong> dice, riéndose incómodamente. <strong>"No pensé que iba a oír estas canciones, sin importar si todos los demás las escuchaban. ¡Pero ahora las escuchará! Probablemente reciba una llamada bastante interesante en algún momento".</strong></p>
        <blockquote>
            <p>El verdadero <strong>Mac,</strong> con verrugas y todo, aparece constantemente en este disco. Ambas partes están acorraladas por canciones efímeras y serias. <strong>"Watching Him Fade Away"</strong> concluye la segunda mitad, mientras que <strong>"Sister"</strong> <i>—un homenaje conmovedor a su media hermana Holly—</i> cierra la primera. También está <strong>"Moonlight on the River",</strong> <i>una extensa de canción que parece hundirse profundamente dentro de su psique.</i> Con siete minutos de duración, la segunda mitad es básicamente el sonido de <strong>DeMarco</strong> gritando en un amplificador, creando un muro de enloquecedora retroalimentación.</p>
        <blockquote>
            <p><strong>"Eso fue como a las 4 de la mañana, yo solo en mi estudio, fumando y riéndome como un imbécil. Fue una escena extraña".</strong> Recuerda el momento con risas, pero la segunda mitad de la canción suena como a un músico trepando por las paredes. Siguiendo su política de honestidad primero, califica el <i>bagel</i> que acaba de consumir. <strong>"No es el mejor que he comido, pero es bastante bueno",</strong> dice, limpiándose la mostaza de la cara. <strong>"Creo que el <i>bagel</i> estaba un poco menos salado que lo normal, lo cual es, ya sabes... Está en el nombre —necesitas sal. Normalmente como estos cuando estoy realmente borracho, después de un show. Hoy estoy completamente sobrio. ¿Sabes qué? Lo disfruté. Ahora entiendo los matices de la carne".</strong></p>
        <blockquote>
            <p>Todavía está analizándolo ligeramente, porque eso es lo que le sale por naturaleza. Menos un mecanismo de defensa y más su modo estándar, el personaje no ha invadido del todo a <strong>DeMarco,</strong> pero amenaza con hacerlo. Sólo se le acerca un fanático a mitad de la entrevista, y la conversación es normal —no hay expectativas de que haga una broma o tome una selfie con una cara graciosa.</p>
        <blockquote>
            <p>Cuando salimos de la tienda de <i>bagels,</i> comienza una conversación con un hombre sin hogar que se encontraba afuera, entregándole un billete de 10 libras una vez que ha buscado cambio en sus bolsillos, antes de meter su guitarra acústica a un taxi para su concierto de hoy por la noche. <strong>"En este caso sólo quería mantenerlo real",</strong> dice, regresando a hablar del disco. <strong>"Eso es lo que se siente bien para mí, así que tal vez a otras personas les guste. Estas canciones son personales para mí, pero si alguien que la escucha no conoce mi historia, no entenderían esa parte. Son lo suficientemente vagas como para que no sepan de qué estoy hablando, pero podrían conectarse a ella de otras maneras. Esa es otra filosofía mía en cuanto a la composición de canciones —mantenlo simple, estúpido".</strong></p>                             
      </div><!-- /.blog-post -->

      <footer class="blog-footer">
  <p>Blog original de <a href="https://www.vice.com/es_latam/article/mbqwba/mac-demarco-perfil-this-old-dog-2017">Vice.com</a></p>
</footer>
</body>
</html>